POST http://localhost:8080/api/users/signup
Content-Type: application/json; charset=UTF-8

{
    "username": "woogi",
    "password": "1234"
}

# # HTTP/1.1 200 
# X-Content-Type-Options: nosniff
# X-XSS-Protection: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# Pragma: no-cache
# Expires: 0
# X-Frame-Options: DENY
# Content-Type: text/plain;charset=UTF-8
# Content-Length: 39
# Date: Mon, 16 Jun 2025 12:03:30 GMT
# Connection: close

# 이미 존재하는 아이디입니다.

# HTTP/1.1 200 
# X-Content-Type-Options: nosniff
# X-XSS-Protection: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# Pragma: no-cache
# Expires: 0
# X-Frame-Options: DENY
# Content-Type: text/plain;charset=UTF-8
# Content-Length: 20
# Date: Mon, 16 Jun 2025 12:04:58 GMT
# Connection: close

# 회원가입 성공.